### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by agalbo** [opengovdata/opengovdata.github.io#5]
Open government data claims to copyright is an issue that is currently in limbo, as we see a social necessity to strike the proper balance between the need for public access to free flowing information and the need to maintain the principles and goals fundamental to intellectual property law. The general, doctrinal takeaway from 1991’s Feist Publications is that facts are not copyrightable, however compilations of facts generally are; "the touchstone of copyright protection" is the component of originality, as per Constitutional requirements. Further, Feist provided interesting commentary on the underlying, policy basis of copyright law, noting that the objective of copyright is not to reward the efforts of authors, but rather to promote “the progress of science and useful arts.”

Clearly the case (and course in general) narrowly discusses the open publication, sharing, and use of non-tangibles: ideas, information, and resources. This past summer, I worked in-house for a fashion brand and worked on intellectual property, specifically brand protection via enforcement of copyright and trademark rights. While I worked in the realm of material goods shared online versus information shared, I see some parallels, conceptually. I frequently found the work to be an uphill battle. Namely, 2010’s Tiffany v. Ebay established that trademark and copyright owners bear the burden of policing for counterfeit items when their products are sold in an online marketplace. This begs the question as to whether similar precedent is applicable to copyrighted code, ideas, legal resources, etc. If so, even if authors boast work with the necessary originality components to acquire copyright protection, such authors would assume the task of indefinitely policing the entire Internet for violations of those copyrights. Moreover, even if those authors do, in fact, find what they believe to be infringing actors, the legal process of evoking relief, while simple in theory, poses difficulties in execution. It essentially becomes the court's discretion as to whether the necessary threshold of originality is present. Nuance differences may not be distinguishable to the courts but are very much distinguishable to one with an artistic vision or to a business enterprise (such as Feist) trying to circumvent copyright law by arranging data in a strategic manner. For example, a seller claiming that, although unapparent to the untrained eye, his or her bracelet is marginally different and original from the name brand version can be analogized to a publisher of data claiming that his or her work is distinct and original in compilation from the original source. Quite simply, legal fact finders who lack expertise in the field (be it art, design, data, or coding) are entrusted with the role of decreeing whether the originality component has been met. While the case law indicates that originality requirement is not particularly stringent and only a narrow category of works that will not pass the test, I would imagine that amongst that narrow category, there are instances in which the originality line is not clear to the legal fact finder but is readily apparent to one with a trained eye, so to speak. Thus, this allows for a slipping through the cracks.

Within the Li piece, an excerpt resonated with me: “in its rawest form, isn’t every single person who participates in the creation of a law or the inclusion by association of the standard, in fact, an author?” While some of the other readings prompted the discussion of what components constitute copyright protection, this changed the course of my analysis towards who qualifies. While Li’s article is specific to the idea of legal code, the same inquiry can obviously be applied to non-legal writings. The Jacobsen case specifically makes mention of Wikipedia and other collaboratively authored and edited works. All things considered, I do see validity in that argument. While (backtracking) the intention of copyright is not, per se, to reward the labor of authors, I do think that there are fairness arguments to be made that every mind that contributed in the creation of work, no matter how minute that contribution, should be considered as an author, of sorts. Thus, privately contracted, legal publishing companies are in no place to withhold statutory or codified information at a cost when they very minds and input, and social of public constituents are what brought those very codes to fruition in the first place. We are living in an era of blurred distinction between government entity and private organization, and subsequently an era of blurred clarity as to the rights and protections of both sectors.

**Comment by vdavez** [comment]
Added per 28db2b8851240e08efda291b448b8294fa5e772d
